#include"lcd.h"
int g_zhang[]={2,0,1,8,0,3,0,2};
int g_mi[]={8,8,8,8,8,8};
struct dirent *mysdir;
struct dirent *myadir;
//进度条
// void show_jin(int a,int b,const char *pathname)
// {
// 	//定义进度条显示的起始位置
	
// 	//显示进度条
// 	while(1)
// 	{
// 	    //显示小图片x  y
//         show_bmp(a,b,pathname);
//         //微秒延时
//         usleep(500000);
//         //更新起点位置
//         a+=40;
//         //如果显示到720停止
//         if(a > 750)
//              break;			
// 	}
// }

//滑动显示图片
void move_bmp()
{
	struct inputxy old,new;
	int m;
	while(1)
	{
		m=get_move(&old,&new);//获取移动方向		
		if(m == MOVE_LEFT)//左边
		{
			printf("滑动在左边\n");
			show_bmp(0,0,"./3.bmp");
		}   
	    if(m == MOVE_UP)//上边
		{
			printf("滑动在上边\n");
			show_bmp(0,0,"./4.bmp");
		}		    
		if(m == MOVE_DOWN)//下边
		{
			printf("滑动在下边\n");
			show_bmp(0,0,"./5.bmp");
		}		    	
		if(m == MOVE_RIGHT)//右边
		{
			printf("滑动在右边\n");	
			show_bmp(0,0,"./6.bmp");
		}		    
	}
}
//购物车添加
void lian(int b,caa heads,caa newnodes)
{
if(b==0)
	{
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"56.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	} 
	newnodes=crivte_newnode_jie(heads,a,56);
	add_tail_jie(heads,newnodes);
	}
if(b==1)
	{
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"68.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	}
	newnodes=crivte_newnode_jie(heads,a,68);
	add_tail_jie(heads,newnodes);
	}
if(b==2)
	{
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"128.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	}
	newnodes=crivte_newnode_jie(heads,a,128);
	add_tail_jie(heads,newnodes);
	}
if(b==3)
	{
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"5yuan.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	}
	newnodes=crivte_newnode_jie(heads,a,5);
	add_tail_jie(heads,newnodes);
	}
if(b==4)
	{
	
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"200.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	}
	newnodes=crivte_newnode_jie(heads,a,200);
	add_tail_jie(heads,newnodes);
	}
if(b==5)
	{	
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"34.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	}
	newnodes=crivte_newnode_jie(heads,a,34);
	add_tail_jie(heads,newnodes);
	}
if(b==6)
	{
		
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"30.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	}
	newnodes=crivte_newnode_jie(heads,a,30);
	add_tail_jie(heads,newnodes);
	}
if(b==7)
	{	
	char *a,*b;
	DIR *mydir=opendir("/IOT");
	while((mysdir=readdir(mydir))!=NULL)
	{
		if(strstr(mysdir->d_name,"24.bmp")!=NULL)
		{
			a=mysdir->d_name;
			break;
		}
	}
	closedir(mydir); 
	newnodes=crivte_newnode_jie(heads,a,24);
	add_tail_jie(heads,newnodes);
	}

}
//登录选择和界面判断
int touch(peo head);
 int touch3(peo head);
int touch1(peo head,peo newnode,caa heads,caa newnodes)
{
	input old,new;
	//选择界面
	show_bmp(0,0,"xunaze.bmp");
	input data;
	int m,n,a=0,b=0,c=0;
	while(a<1)
	{
	m=get_xy(&data);
	//VIP
if (m==1)
	{
		a++;
		show_bmp(0,0,"guan.bmp");
		//输入账户密码并且判断
		m=touch(head);
	 if(m==-1)
	{
		show_bmp(255,70,"zm.bmp");
		return -1;
	}
	if(m==0)
	{
	
		show_bmp(0,0,"VIP.bmp");
		sleep(1);
		a++;
		//第一页菜单
		show_bmp(0,0,"VIP.bmp");
		show_bmp(0,0,"caidan.bmp");
		little_bmp(0,0,"fried.bmp");
		little_bmp(0,190,"56.bmp");
		little_bmp(450,0,"meat.bmp");
		little_bmp(450,190,"68.bmp");
		little_bmp(0,290,"prawn.bmp");
		little_bmp(0,240,"128.bmp");
		show_bmp(450,290,"rice.bmp");
		little_bmp(450,240,"5yuan.bmp");
		show_bmp(350,190,"left.bmp");
		show_bmp(390,190,"right.bmp");
		little_bmp(350,380,"cai.bmp");
		while(b<1)
			{
				perror("===");
				m=get_xy_cai(&data);
				if(m==0)
					{
				lian(0,heads,newnodes);
				show_bmp(350,380,"+1.bmp");
				sleep(1);
				little_bmp(350,380,"cai.bmp");
					}
				if(m==1)
				{
				lian(1,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==2)
				{
					lian(2,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==3)
				{
					lian(3,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==4)
				{
					b++;
					touch1(head,newnode,heads,newnodes);
					return 0;
				}
				if(m==5)
				{
						//第二页菜单
						b++;
					show_bmp(0,0,"longxia.bmp");
					show_bmp(0,190,"200.bmp");
					show_bmp(450,0,"luosi.bmp");
					show_bmp(450,190,"34.bmp");
					show_bmp(0,290,"rou.bmp");
					show_bmp(0,240,"30.bmp");
					show_bmp(450,290,"zhaji.bmp");
					show_bmp(450,240,"24.bmp");
					show_bmp(350,190,"left.bmp");
					little_bmp(350,380,"cai.bmp");
					while(c<1)
					{
					m=get_xy_cai(&data);
						if(m==0)
						{
							lian(4,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==1)
						{
							lian(5,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==2)
						{
							lian(6,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==3)
						{
							lian(7,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==4)
						{	c++;
							touch1(head,newnode,heads,newnodes);
						} 
					}
				}
				if(m==6)
				{
					show_jie(heads);
					show_bmp(350,190,"left.bmp");
					c=0;
				while(c<1)
					{
						m=get_xy_cai(&data);
					
						if(m==4)
						{
							touch1(head,newnode,heads,newnodes);
						}
					}
				}
			}
	}
	}
	//普通用户
if(m==0)
	{
	a++;
		//第一页菜单
		show_bmp(0,0,"VIP.bmp");
		show_bmp(0,0,"caidan.bmp");
		little_bmp(0,0,"fried.bmp");
		little_bmp(0,190,"56.bmp");
		little_bmp(450,0,"meat.bmp");
		little_bmp(450,190,"68.bmp");
		little_bmp(0,290,"prawn.bmp");
		little_bmp(0,240,"128.bmp");
		show_bmp(450,290,"rice.bmp");
		little_bmp(450,240,"5yuan.bmp");
		show_bmp(350,190,"left.bmp");
		show_bmp(390,190,"right.bmp");
		little_bmp(350,380,"cai.bmp");
		while(b<1)
			{
				perror("===");
				m=get_xy_cai(&data);
				if(m==0)
					{
				lian(0,heads,newnodes);
				show_bmp(350,380,"+1.bmp");
				sleep(1);
				little_bmp(350,380,"cai.bmp");
					}
				if(m==1)
				{
				lian(1,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==2)
				{
					lian(2,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==3)
				{
					lian(3,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==4)
				{
					b++;
					touch1(head,newnode,heads,newnodes);
					return 0;
				}
				if(m==5)
				{
						//第二页菜单
						b++;
					show_bmp(0,0,"longxia.bmp");
					show_bmp(0,190,"200.bmp");
					show_bmp(450,0,"luosi.bmp");
					show_bmp(450,190,"34.bmp");
					show_bmp(0,290,"rou.bmp");
					show_bmp(0,240,"30.bmp");
					show_bmp(450,290,"zhaji.bmp");
					show_bmp(450,240,"24.bmp");
					show_bmp(350,190,"left.bmp");
					little_bmp(350,380,"cai.bmp");
					while(c<1)
					{
					m=get_xy_cai(&data);
						if(m==0)
						{
							lian(4,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==1)
						{
							lian(5,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==2)
						{
							lian(6,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==3)
						{
							lian(7,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==4)
						{	c++;
							touch1(head,newnode,heads,newnodes);
						} 
					}
				}
				if(m==6)
				{
					show_jie(heads);
					show_bmp(350,190,"left.bmp");
					c=0;
				while(c<1)
					{
						m=get_xy_cai(&data);
					
						if(m==4)
						{
							touch1(head,newnode,heads,newnodes);
						}
					}
				}
			}
	}
	
	//管理员
if(m==2)
	{
		a++;
		show_bmp(0,0,"guan.bmp");
		//输入账户密码并且判断
		m=touch3(head);
	if(m==-1)
	{
		show_bmp(255,70,"zm.bmp");
		touch1(head,newnode,heads,newnodes);
		return -1;
	}
	if(m==0)
	{
		show_bmp(0,0,"VIP.bmp");
		a++;
		//第一页菜单
		show_bmp(0,0,"VIP.bmp");
			show_bmp(0,0,"caidan.bmp");
			little_bmp(0,0,"fried.bmp");
			little_bmp(0,190,"56.bmp");
			little_bmp(450,0,"meat.bmp");
			little_bmp(450,190,"68.bmp");
			little_bmp(0,290,"prawn.bmp");
			little_bmp(0,240,"128.bmp");
			show_bmp(450,290,"rice.bmp");
			little_bmp(450,240,"5yuan.bmp");
			show_bmp(350,190,"left.bmp");
		show_bmp(390,190,"right.bmp");
		little_bmp(350,380,"cai.bmp");
		while(b<1)
			{
				perror("===");
				m=get_xy_cai(&data);
				if(m==0)
					{
				lian(0,heads,newnodes);
				show_bmp(350,380,"+1.bmp");
				sleep(1);
				little_bmp(350,380,"cai.bmp");
					}
				if(m==1)
				{
				lian(1,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==2)
				{
					lian(2,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==3)
				{
					lian(3,heads,newnodes);
					show_bmp(350,380,"+1.bmp");
					sleep(1);
					little_bmp(350,380,"cai.bmp");
				}
				if(m==4)
				{
					b++;
					touch1(head,newnode,heads,newnodes);
					return 0;
				}
				if(m==5)
				{
						//第二页菜单
						b++;
					show_bmp(0,0,"longxia.bmp");
					show_bmp(0,190,"200.bmp");
					show_bmp(450,0,"luosi.bmp");
					show_bmp(450,190,"34.bmp");
					show_bmp(0,290,"rou.bmp");
					show_bmp(0,240,"30.bmp");
					show_bmp(450,290,"zhaji.bmp");
					show_bmp(450,240,"24.bmp");
					show_bmp(350,190,"left.bmp");
					little_bmp(350,380,"cai.bmp");
					while(c<1)
					{
					m=get_xy_cai(&data);
						if(m==0)
						{
							lian(4,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==1)
						{
							lian(5,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==2)
						{
							lian(6,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==3)
						{
							lian(7,heads,newnodes);
							show_bmp(350,380,"+1.bmp");
							sleep(1);
							little_bmp(350,380,"cai.bmp");
						}
						if(m==4)
						{	c++;
							touch1(head,newnode,heads,newnodes);
						} 
					}
				}
				if(m==6)
				{
					show_jie(heads);
					show_bmp(350,190,"left.bmp");
					c=0;
				while(c<1)
					{
						m=get_xy_cai(&data);
					
						if(m==4)
						{
							touch1(head,newnode,heads,newnodes);
						}
					}
				}
			}
		}
	}
	//注册
		if(m==3)
		{
			a++;
			show_bmp(0,0,"guan.bmp");
			m=touch2(head,newnode);
			sleep(2);
		touch1(head,newnode,heads,newnodes);
			return 3;
		}
	}
}
//单击获取
int pan(peo head,int a[],int b[],int c,int d);
//VIP账户密码判断
 int touch(peo head)
 {		
		int b[8],c[6];
		input data;
		int m,i=255,a=0;
		//账户
		while(a<8)
		{
			m=get_xy_lu(&data);
			b[a]=m;
			
			if(m==0)
			{
					a++;
			show_bmp(i,70,"0.bmp");
			i+=40;
			}
			if(m==1)
			{
					a++;
			show_bmp(i,70,"1.bmp");
			i+=40;
			}
			if(m==2)
			{
					a++;
			show_bmp(i,70,"2.bmp");
			i+=40;
			}
			if(m==3)
			{
					a++;
			show_bmp(i,70,"3.bmp");
			i+=40;
			}
			if(m==4)
			{
					a++;
			show_bmp(i,70,"4.bmp");
			i+=40;
			}
			if(m==5)
			{
					a++;
			show_bmp(i,70,"5.bmp");
			i+=40;
			}
			if(m==6)
			{
					a++;
			show_bmp(i,70,"6.bmp");
			i+=40;
			}
			if(m==7)
			{
					a++;
			show_bmp(i,70,"7.bmp");
			i+=40;
			}
			if(m==8)
			{
					a++;
			show_bmp(i,70,"8.bmp");
			i+=40;
			}
			if(m==9)
			{
					a++;
			show_bmp(i,70,"9.bmp");
			i+=40;
			}
			if(m==10)
			{
					a++;
			show_bmp(i,70,"10.bmp");
			i+=40;
			}
			if(m==11)
			{
					a++;
			show_bmp(i,70,"11.bmp");
			i+=40;
			}
		}
		a=0;
		i=255;
		//密码
		while(a<6)
		{
			m=get_xy_lu(&data);
			c[a]=m;
					
			if(m==0)
			{
				a++;
			show_bmp(i,170,"0.bmp");
			i+=40;
			}
			if(m==1)
			{
				a++;
			show_bmp(i,170,"1.bmp");
			i+=40;
			}
			if(m==2)
			{
				a++;
			show_bmp(i,170,"2.bmp");
			i+=40;
			}
			if(m==3)
			{
				a++;
			show_bmp(i,170,"3.bmp");
			i+=40;
			}
			if(m==4)
			{
				a++;
			show_bmp(i,170,"4.bmp");
			i+=40;
			}
			if(m==5)
			{
				a++;
			show_bmp(i,170,"5.bmp");
			i+=40;
			}
			if(m==6)
			{
				a++;
			show_bmp(i,170,"6.bmp");
			i+=40;
			}
			if(m==7)
			{
				a++;
			show_bmp(i,170,"7.bmp");
			i+=40;
			}
			if(m==8)
			{
				a++;
			show_bmp(i,170,"8.bmp");
			i+=40;
			}
			if(m==9)
			{
				a++;
			show_bmp(i,170,"9.bmp");
			i+=40;
			}
			if(m==10)
			{
				a++;
			show_bmp(i,170,"10.bmp");
			i+=40;
			}
			if(m==11)
			{
				a++;
			show_bmp(i,170,"11.bmp");
			i+=40;
			}
		}
		return pan(head,b,c,8,6);
 }

 //账户密码判断
int pan(peo head,int a[],int b[],int c,int d)
{
	show(head);
	int i;
	peo p=head;
	while(p->next!=head)
	{
		
		p=p->next;
		for(i=0;i<8;i++)
		{
			if(p->zhang[i]!=a[i])
			{
				break;
			}
		}
		if(i==8)
		{
			break;
		}
	}
	if(i!=8)
	{
	return -1;
	}
	for(i=0;i<6;i++)
	{
		if(p->mi[i]!=b[i])
		{
			break;
		}
	}
	if(i!=6)
	{
		return -1;
	}
	return 0;
}
/* =================================== */
//注册登录
int touch2(peo head,peo newnode)
 {		
		int b[8],c[6];
		input data;
		int m,i=255,a=0;
		//账户
		while(a<8)
		{
	 	m=get_xy_lu(&data);
		b[a]=m;
		if(m==0)
		{
			a++;
		show_bmp(i,70,"0.bmp");
		i+=40;
		}
		if(m==1)
		{
			a++;
		show_bmp(i,70,"1.bmp");
		i+=40;
		}
		if(m==2)
		{
			a++;
		show_bmp(i,70,"2.bmp");
		i+=40;
		}
		if(m==3)
		{
			a++;
		show_bmp(i,70,"3.bmp");
		i+=40;
		}
		if(m==4)
		{
			a++;
		show_bmp(i,70,"4.bmp");
		i+=40;
		}
		if(m==5)
		{
			a++;
		show_bmp(i,70,"5.bmp");
		i+=40;
		}
		if(m==6)
		{
			a++;
		show_bmp(i,70,"6.bmp");
		i+=40;
		}
		if(m==7)
		{
			a++;
		show_bmp(i,70,"7.bmp");
		i+=40;
		}
		if(m==8)
		{
			a++;
		show_bmp(i,70,"8.bmp");
		i+=40;
		}
		if(m==9)
		{
			a++;
		show_bmp(i,70,"9.bmp");
		i+=40;
		}
		if(m==10)
		{
			a++;
		show_bmp(i,70,"10.bmp");
		i+=40;
		}
		if(m==11)
		{
			a++;
		show_bmp(i,70,"11.bmp");
		i+=40;
		}
		}
		a=0;
		i=255;
		//密码
		while(a<6)
		{
			m=get_xy_lu(&data);
			c[a]=m;
		
		if(m==0)
		{
		a++;
		show_bmp(i,170,"0.bmp");
		i+=40;
		}
		if(m==1)
		{
		a++;
		show_bmp(i,170,"1.bmp");
		i+=40;
		}
		if(m==2)
		{
			a++;
		show_bmp(i,170,"2.bmp");
		i+=40;
		}
		if(m==3)
		{
			a++;
		show_bmp(i,170,"3.bmp");
		i+=40;
		}
		if(m==4)
		{
			a++;
		show_bmp(i,170,"4.bmp");
		i+=40;
		}
		if(m==5)
		{
			a++;
		show_bmp(i,170,"5.bmp");
		i+=40;
		}
		if(m==6)
		{
			a++;
		show_bmp(i,170,"6.bmp");
		i+=40;
		}
		if(m==7)
		{
			a++;
		show_bmp(i,170,"7.bmp");
		i+=40;
		}
		if(m==8)
		{
			a++;
		show_bmp(i,170,"8.bmp");
		i+=40;
		}
		if(m==9)
		{
			a++;
		show_bmp(i,170,"9.bmp");
		i+=40;
		}
		if(m==10)
		{
			a++;
		show_bmp(i,170,"10.bmp");
		i+=40;
		}
		if(m==11)
		{
			a++;
		show_bmp(i,170,"11.bmp");
		i+=40;
		}
		}
		//注册
		int n=pan(head,b,c,8,6);
		if(n==-1)
		{
			newnode=crivte_newnode(head,b,c,8,6);
			add_tail(head,newnode);
			   show_jin("jin.bmp");
			show_bmp(0,0,"chenggong.bmp");
			return 0;
		}
		else
		{	
	   show_jin("jin.bmp");
		show_bmp(0,0,"shibai.bmp");
		return -1;
		}
 }
 //管理员登录
 int touch3(peo head)
 {		
		int b[8],c[6];
		input data;
		int m,i=255,a=0;
		//账户
		while(a<8)
		{
	 	m=get_xy_lu(&data);
		b[a]=m;
			
		if(m==0)
		{
			a++;
		show_bmp(i,70,"0.bmp");
		i+=40;
		}
		if(m==1)
		{
			a++;
		show_bmp(i,70,"1.bmp");
		i+=40;
		}
		if(m==2)
		{
			a++;
		show_bmp(i,70,"2.bmp");
		i+=40;
		}
		if(m==3)
		{
			a++;
		show_bmp(i,70,"3.bmp");
		i+=40;
		}
		if(m==4)
		{
			a++;
		show_bmp(i,70,"4.bmp");
		i+=40;
		}
		if(m==5)
		{
			a++;
		show_bmp(i,70,"5.bmp");
		i+=40;
		}
		if(m==6)
		{
			a++;
		show_bmp(i,70,"6.bmp");
		i+=40;
		}
		if(m==7)
		{
			a++;
		show_bmp(i,70,"7.bmp");
		i+=40;
		}
		if(m==8)
		{
			a++;
		show_bmp(i,70,"8.bmp");
		i+=40;
		}
		if(m==9)
		{
			a++;
		show_bmp(i,70,"9.bmp");
		i+=40;
		}
		if(m==10)
		{
			a++;
		show_bmp(i,70,"10.bmp");
		i+=40;
		}
		if(m==11)
		{
			a++;
		show_bmp(i,70,"11.bmp");
		i+=40;
		}
		}
		a=0;
		i=255;
		//密码
		while(a<6)
		{
			m=get_xy_lu(&data);
			c[a]=m;
				
		if(m==0)
		{
			a++;
		show_bmp(i,170,"0.bmp");
		i+=40;
		}
		if(m==1)
		{
			a++;
		show_bmp(i,170,"1.bmp");
		i+=40;
		}
		if(m==2)
		{
			a++;
		show_bmp(i,170,"2.bmp");
		i+=40;
		}
		if(m==3)
		{
			a++;
		show_bmp(i,170,"3.bmp");
		i+=40;
		}
		if(m==4)
		{
			a++;
		show_bmp(i,170,"4.bmp");
		i+=40;
		}
		if(m==5)
		{
			a++;
		show_bmp(i,170,"5.bmp");
		i+=40;
		}
		if(m==6)
		{
			a++;
		show_bmp(i,170,"6.bmp");
		i+=40;
		}
		if(m==7)
		{
			a++;
		show_bmp(i,170,"7.bmp");
		i+=40;
		}
		if(m==8)
		{
			a++;
		show_bmp(i,170,"8.bmp");
		i+=40;
		}
		if(m==9)
		{
			a++;
		show_bmp(i,170,"9.bmp");
		i+=40;
		}
		if(m==10)
		{
			a++;
		show_bmp(i,170,"10.bmp");
		i+=40;
		}
		if(m==11)
		{
			a++;
		show_bmp(i,170,"11.bmp");
		i+=40;
		}
		}
		show2(b,c,8,6);
		show2(g_zhang,g_mi,8,6);
		//判断管理员账户
		for(i=0;i<8;i++)
		{
			if(b[i]!=g_zhang[i])
			{
				break;
			}
		}
		if(i!=8)
		{
			return -1;
		}
		for(i=0;i<6;i++)
			{
					if(c[i]!=g_mi[i])
					break;
			}
			if(i!=6)
			return -1;
			return 0;
 }
